services:
  postgres:
    image: postgres:16
    container_name: bifrost-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ccb_lotacao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bifrost-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ccb_lotacao"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  bifrost-network:
    driver: bridge
